#!/usr/bin/env bash
#  ╔═╗═╗ ╦╔╦╗╔═╗╦═╗╔╗╔╔═╗╦    ╦═╗╦ ╦╦  ╔═╗╔═╗
#  ║╣ ╔╩╦╝ ║ ║╣ ╠╦╝║║║╠═╣║    ╠╦╝║ ║║  ║╣ ╚═╗
#  ╚═╝╩ ╚═ ╩ ╚═╝╩╚═╝╚╝╩ ╩╩═╝  ╩╚═╚═╝╩═╝╚═╝╚═╝
#  https://github.com/gh0stzk/dotfiles

wid=$1
class=$2
instance=$3
consequences=$4

	case "$class" in
		Updating)
			eval "$consequences"
			[ "$state" ] || echo "state=floating sticky=on center=on"
			;;
		mpv)
			eval "$consequences"
			[ "$state" ] || echo "state=floating focus=on rectangle=849x477+0+0 center=on"
			;;
		Viewnior)
			eval "$consequences"
			[ "$state" ] || echo "state=floating focus=on center=on"
			;;
		whatsapp-nativefier-d40211|TelegramDesktop)
			eval "$consequences"
			[ "$state" ] || echo "state=pseudo_tiled desktop=^4 follow=on rectangle=930x617+0+0"
			;;
		retroarch)
			eval "$consequences"
			[ "$state" ] || echo "state=pseudo_tiled desktop=^6 follow=on"
			;;
		Pavucontrol)
			eval "$consequences"
			[ "$state" ] || echo "state=floating center=on"
			;;
		Virt-manager)
			eval "$consequences"
			[ "$state" ] || echo "state=floating desktop=^5 follow=on center=on"
			;;
		Thunar)
			eval "$consequences"
			[ "$state" ] || echo "state=pseudo_tiled desktop=^2 rectangle=966x576+0+0 follow=on"
			;;
		Brave-browser)
			eval "$consequences"
			[ "$state" ] || echo "desktop=3 follow=on"
			;;
		transmission-gtk)
			eval "$consequences"
			[ "$state" ] || echo "desktop=^6 follow=on"
			;;
		Spotify)
			eval "$consequences"
			[ "$state" ] || echo "state=pseudo_tiled desktop=6 follow=on rectangle=980x700+0+0"
			;;
		FloaTerm)
                        eval "$consequences"
                        [ "$state" ] || echo "state=pseudo_tiled desktop=6"
                        ;;
		Code)
                        eval "$consequences"
                        [ "$state" ] || echo "state=tiled desktop=2"
                        ;;
		
		discord)
                        eval "$consequences"
                        [ "$state" ] || echo "state=tiled desktop=5 "
                        ;;

		Big-Store)
                        eval "$consequences"
                        [ "$state" ] || echo "state=pseudo_tiled desktop=6 follow=on"
                        ;;
		obs)
                        eval "$consequences"
                        [ "$state" ] || echo "state=pseudo_tiled desktop=5 follow=on"
                        ;;
		qBittorrent)
                        eval "$consequences"
                        [ "$state" ] || echo "state=pseudo_tiled desktop=6"
                        ;;
		krita)
                        eval "$consequences"
                        [ "$state" ] || echo "state=pseudo_tiled follow=on desktop=4"
                        ;;
		dolphin)
                        eval "$consequences"
                        [ "$state" ] || echo "state=pseudo_tiled follow=on desktop=1 rectangle=980x700+0+0"
                        ;;
		vlc)
                        eval "$consequences"
                        [ "$state" ] || echo "state=pseudo_tiled follow=on desktop=1"
                        ;;
		"Weston Compositor")
                        eval "$consequences"
                        [ "$state" ] || echo "state=tiled follow=on desktop=1"
                        ;;
	esac

	case "$instance" in
		Toolkit)
			eval "$consequences"
			[ "$state" ] || echo "state=floating sticky=on rectangle=500x290+1054+593"
			;;
	esac  
